##spring:
##  datasource:
##    url: 
##    username: 
##    password: 
##    driver-class-name: oracle.jdbc.OracleDriver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
    username: root
    password: Oldreserve12#
    driver-class-name: com.mysql.jdbc.Driver