##spring:
##  datasource:
##    url: 
##    username: 
##    password: 
##    driver-class-name: oracle.jdbc.OracleDriver

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?createDatabaseIfNotExist=true
    username: root
    password: Oldreserve12#
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate: 
        show_sql: true
        format_sql: true